server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://localhost:8000/eureka/"
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

security:
  basic:
    enable: true
  user:
    name: root
    password: eureka