spring:
  application:
    name: EurekaServer

#security:
#  basic:
#    enable: true
#  user:
#    name: root
#    password: eureka
---
spring:
  profiles: default

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://192.168.27.129:8000/eureka/"
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 100000
  instance:
    prefer-ip-address: true


---
spring:
  profiles: sub

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://192.168.27.128:8000/eureka/"
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 100000
  instance:
    prefer-ip-address: true
