spring:
  application:
    name: SpringCloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/otter2017/Config  
          
server:
  port: 8000
  
version: 17.10.24

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:eureka@localhost/eureka/
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

security:
  basic:
    enable: true
  user:
    name: root
    password: configserver